"""autogen-after-fix

Revision ID: 1959dd97a87f
Revises: 0001_initial
Create Date: 2026-05-18 13:05:23.832006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1959dd97a87f'
down_revision: Union[str, Sequence[str], None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: create initial tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('storage_key', sa.VARCHAR(length=500), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ats_score', sa.INTEGER(), nullable=False),
    sa.Column('semantic_match', sa.FLOAT(), nullable=False),
    sa.Column('parsed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('resume_versions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('resume_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('version_label', sa.VARCHAR(length=100), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('ats_score', sa.INTEGER(), nullable=False),
    sa.Column('semantic_match', sa.FLOAT(), nullable=False),
    sa.Column('source_notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_versions_resume_id'), 'resume_versions', ['resume_id'], unique=False)
    op.create_table('analytics',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('resume_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_resume_id'), 'analytics', ['resume_id'], unique=False)
    op.create_table('job_descriptions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('company', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('normalized_text', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_descriptions_user_id'), 'job_descriptions', ['user_id'], unique=False)
    op.create_table('interview_questions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('resume_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('question', sa.TEXT(), nullable=False),
    sa.Column('tone', sa.VARCHAR(length=100), nullable=True),
    sa.Column('bookmarked', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_questions_resume_id'), 'interview_questions', ['resume_id'], unique=False)
    op.create_table('ai_feedback',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('resume_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('mode', sa.VARCHAR(length=50), nullable=False),
    sa.Column('prompt', sa.TEXT(), nullable=True),
    sa.Column('response_text', sa.TEXT(), nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_feedback_resume_id'), 'ai_feedback', ['resume_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('auth_provider', sa.VARCHAR(length=50), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: drop all initial tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ai_feedback_resume_id'), table_name='ai_feedback')
    op.drop_table('ai_feedback')
    op.drop_index(op.f('ix_interview_questions_resume_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index(op.f('ix_job_descriptions_user_id'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    op.drop_index(op.f('ix_analytics_resume_id'), table_name='analytics')
    op.drop_table('analytics')
    op.drop_index(op.f('ix_resume_versions_resume_id'), table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    # ### end Alembic commands ###
